- .github/workflows/ci.yml
- Lubycon Github Reviewer Slack Notify setup
> chore: 👋 Lubycon Github Reviewer Slack Notify setup

- .github/workflows/slack-noti.yml
Slack Notify version update 1.2.0 to 1.2.1
> chore: 👋 Lubycon Github Reviewer Slack Notify version update 1.2.0 to 1.2.1 

- package.json
- src/components/atoms/Banner.tsx
- src/components/atoms/Header.tsx
- src/components/atoms/Text/index.tsx
- src/components/atoms/Timer.tsx
- src/pages/index.tsx
- src/utils/dateTime.ts
- 메인 화면 배너
- timer (hour12, 시간  부분을 다르게 처리하는 법이 있을까요?)
> Feature/#6/banner 

- src/constants/firebase.ts
- src/utils/amplitude.ts
> fix: Google Analytics, Amplitude 환경변수 수정 

- src/GlobalStyles.tsx
- src/components/atoms/SidebarItem.tsx
- src/components/molecules/CourseCard.tsx
- src/components/molecules/SectionRow.tsx
- src/components/organisms/Sidebar.tsx
- src/components/templates/IntroSection.tsx
- src/components/templates/Layout.tsx
- src/pages/course/[courseId]/[sectionId]/index.tsx
- 임시 타이틀 , content. 가 하드 코딩 데이터가 있습니다.
> feature: Intro section  왜 배워야 할까 컨텐츠 1차 안

- package.json
- src/pages/_app.tsx
- yarn.lock
Sentry 추가 및 적용
[React-Sentry](https://docs.sentry.io/platforms/javascript/guides/react/?_ga=2.85076697.1147161820.1621951812-285183696.1618905777&_gac=1.162203470.1619256174.CjwKCAjwg4-EBhBwEiwAzYAlslK53TEAKfyi2OqZvzyiJAjVDM7eXrEqu62pq_y7koZXsd4XA6P4hRoC2pAQAvD_BwE)
> feature: Sentry 에러 추적 추가 

- src/pages/course/[courseId]/[sectionId]/index.tsx
- src/pages/course/[courseId]/index.tsx
코스, 코스 섹션, meta, title, description 추가
> Feature: 코스, 코스 섹션, meta, title, description 추가

- .eslintrc
- src/components/atoms/CompanyItem.tsx
- src/components/atoms/Icon/svg/index.ts
- src/components/atoms/Icon/svg/square.svg
- src/components/atoms/Text/index.tsx
- src/components/organisms/MajorCompanyList.tsx
- src/components/organisms/Statistics.tsx
- src/components/templates/IntroSection.tsx
- src/hooks/api/useGetSections.ts
- src/pages/course/[courseId]/index.tsx
> Feature: 인트로 섹션 트렌드 지표 추가 

- src/components/atoms/CompanyItem.tsx
- src/components/molecules/CourseCard.tsx
- src/components/organisms/MajorCompanyList.tsx
- src/components/organisms/Statistics.tsx
- src/components/templates/IntroSection.tsx
- src/lib/styles/media.ts
- src/pages/course/[courseId]/[sectionId]/index.tsx
- description hardcode to description data
- designer (태룡님 피드백 수정) 
- CompanyItem 수정 (모바일 425) 가운데 정렬
- minor margin 수정
> FIX/ 2차 릴리즈 디자인  QA 반영

- src/pages/course/[courseId]/index.tsx
이벤트 로그에 `utm_source` 값을 추가합니다.
🙇‍♂️
> feat: 이벤트 로그에 utm_source 추가

- src/components/atoms/Banner.tsx
- src/components/atoms/Button.tsx
- src/components/atoms/CompanyItem.tsx
- src/components/atoms/Header.tsx
- src/components/atoms/SidebarItem.tsx
- src/components/atoms/Text/index.tsx
- src/components/atoms/Timer.tsx
- src/components/molecules/CourseCard.tsx
- src/components/molecules/IconButton.tsx
- src/components/molecules/SectionRow.tsx
- src/components/molecules/StickyButton.tsx
- src/components/organisms/CourseList.tsx
- src/components/organisms/MajorCompanyList.tsx
- src/components/organisms/MobileSectionHeader.tsx
- src/components/organisms/Sidebar.tsx
- src/components/organisms/Statistics.tsx
- src/components/templates/IntroSection.tsx
- src/components/templates/Layout.tsx
- src/components/templates/LayoutResponsive.tsx
- src/hooks/api/useGetCoruse.ts
- src/hooks/api/useGetSectionDetail.ts
- src/hooks/api/useGetSections.ts
- src/pages/_app.tsx
- src/pages/course/[courseId]/[sectionId]/index.tsx
- src/pages/course/[courseId]/index.tsx
- src/pages/index.tsx
- tsconfig.json
제곧내입니다.
- `tsconfig`에 `baseUrl` 속성 추가
- 모듈 경로를 절대경로로 변경
단순 Replace입니다. 🙇‍♂️
🙇‍♂️
> refactor: Relative Path를 전부 Absolute Path로 변경

- src/hooks/api/useGetSectionDetail.ts
- src/hooks/api/useGetSections.ts
- src/pages/_app.tsx
- src/pages/_document.tsx
`_document.tsx` 에서 Fully Static하지 않은 속성들을 `_app.tsx`로 옮깁니다.
[Next Docs 참고](https://nextjs.org/docs/messages/no-document-title)
🙇‍♂️
🙇‍♂️
> fix: remove invalid html props in documents

- .github/workflows/slack-noti.yml
github-reviewer-slack-noti-action settings
1.3.0 업데이트
> Chore: lubycon Slack Notify Action v1.3.0 update

- src/components/atoms/Button.tsx
- src/components/molecules/StickyButton.tsx
- src/pages/course/[courseId]/[sectionId]/index.tsx
- 디자인 깨지는 부분 (graphQL 컨텐츠에서 깨짐현상)
- button 사이값 수정 (16 -> 6)
> Fix 디자인 깨지는 부분 및 button 사이값 수정

- src/components/atoms/Button.tsx
- src/components/atoms/SidebarItem.tsx
- src/components/atoms/Sticky.tsx
- src/components/molecules/StickyButton.tsx
- src/components/organisms/Sidebar.tsx
- src/components/templates/IntroSection.tsx
- src/lib/styles/palette.ts
- button 안에 h6 cursor pointer 추가
- hover 애니메이션 추가
- sticky button 영역 수정
> fix: 디자인 영역 수정 및 버튼 애니메이션 수정

- src/components/atoms/Sticky.tsx
- src/components/organisms/MobileSectionHeader.tsx
- src/components/organisms/Sidebar.tsx
- 코스 제목 깨짐 수정
- 모바일 button 사이즈 수정
> fix: UI 깨짐 수정 FIXED

- src/components/atoms/SubcribeForm.tsx
> feat: 이메일 구독 이벤트 로그 추가 

- src/pages/course/[courseId]/[sectionId]/index.tsx
- src/pages/course/[courseId]/index.tsx
> Feat: ld+json structure

- src/components/atoms/SubcribeForm.tsx
- src/components/organisms/MainFooter.tsx
> Feature: 디자인 minor 수정 및 문구 수정

- src/components/molecules/StickyButton.tsx
- src/components/organisms/Sidebar.tsx
- src/components/templates/IntroSection.tsx
- src/components/templates/LayoutResponsive.tsx
- src/pages/course/[courseId]/[sectionId]/index.tsx
> Main에 먼저 배포 나가서 Stage Merge PR입니다!

- .github/CODEOWNERS
> chore: 코드 오너 수정 및 건상님 추가

- src/components/molecules/SectionRow.tsx
코스 섹션에 string html tag 적용할 수 있도록 수정
> Release: Deploy production

- package.json
- src/components/atoms/SubcribeForm.tsx
- src/components/organisms/MainFooter.tsx
- src/components/templates/IntroSection.tsx
- src/constants/firebase.ts
- src/pages/_app.tsx
- src/pages/course/[courseId]/[sectionId]/index.tsx
- src/pages/course/[courseId]/index.tsx
- src/pages/index.tsx
- yarn.lock
유틸 관련 기능이 모두 묶여있는 `@lubycon/utils`를 제거하고, 현재 클랩에서 사용하고 있는 기능인 로거 디펜던시만 물고있는 `@lubycon/logger`로 변경합니다.
🙇‍♂️
> chore: lubycon 관련 라이브러리 업데이트

- src/hooks/api/useGetSectionDetail.ts
- src/hooks/api/useGetSections.ts
> fix: api fetch parameters 변경

- src/components/atoms/SidebarItem.tsx
- src/components/organisms/Sidebar.tsx
- src/components/templates/IntroSection.tsx
- src/hooks/api/useGetSectionDetail.ts
- src/hooks/api/useGetSections.ts
- src/pages/_app.tsx
- src/pages/course/[courseSlug]/[sectionSlug]/index.tsx
- src/pages/course/[courseSlug]/index.tsx
- src/utils/redirectUrl.ts
> 동욱님 코드와 머지 작업

- .github/workflows/pr-notification.yml
- mattermost noti 설정
- Lubycon/github-reviewer-noti-action@v2.0.1 버전 update
> chore: github notify action 2.0.1  update

- src/components/atoms/MainLogo.tsx
- src/components/organisms/MobileSectionHeader.tsx
- src/pages/course/[courseSlug]/index.tsx
- chrome logo color 값이 안나옴 현상
- mobile, web 분리해서 메인로고 출력 
[as-is]
[to-be]
> fix: chrome logo 깨짐 현상 수정

- public/robots.txt
- src/components/organisms/MainFooter.tsx
- robots txt Sitemap 경로 수정 (https://github.com/Lubycon/clelab-frontend/pull/57#discussion_r684614411)
- Footer input css minor 수정
> fix: robots sitemap.xml 수정, footer css minor 수정

- public/robots.txt
- src/components/organisms/MainFooter.tsx
- src/pages/course/[courseSlug]/[sectionSlug]/index.tsx
- course 메인로고 겹치는 현상수정 (#62)
- robots sitemap url 수정, footer css 수정 (#63)
> Release: Deploy production (202132)

- src/components/atoms/Banner.tsx
- src/components/atoms/CompanyItem.tsx
- src/components/atoms/Header.tsx
- src/components/atoms/Input.tsx
- src/components/atoms/InputBase.tsx
- src/components/atoms/Modal.tsx
- src/components/atoms/SidebarItem.tsx
- src/components/atoms/SubcribeForm.tsx
- src/components/atoms/Timer.tsx
- src/components/molecules/CourseCard.tsx
- src/components/organisms/MainFooter.tsx
- src/components/organisms/MajorCompanyList.tsx
- src/components/organisms/MobileSectionHeader.tsx
- src/components/organisms/Sidebar.tsx
- src/hooks/api/useSubscribe.ts
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/pages/course/[courseSlug]/index.tsx
- src/pages/index.tsx
> Fix: 구글 서치콘솔 meta tag 추가 및 baseUrl 수정

- src/components/templates/IntroSection.tsx
> fix: 왜 배워야할까 footer flex 제거

- src/hooks/api/useGetSectionDetail.ts
- src/hooks/api/useGetSections.ts
- 쓰지 않고 있는 verisioning 제거 (v2 제거)
> enh: v2 API 제거

- src/components/templates/IntroSection.tsx
- src/hooks/api/useGetSectionDetail.ts
- src/hooks/api/useGetSections.ts
> Release: Deploy production (202132) api version  제거

- .gitignore
- public/robots.txt
- public/sitemap.xml
https://github.com/Lubycon/clelab-frontend/issues/71
위 이슈에 대한 수정 사항입니다.
QA 서버가 크롤링이 되고 있는 이슈가 있었고 변경될 가능성이 적은 robots.txt 파일을 QA서버에 삭제하고 gitignore에 robost.txt를 추가해줬습니다.
🙏
> fix: robots.txt 파일 삭제 및 사이트맵 수정

- src/components/molecules/ArticleCard.tsx
- src/components/molecules/SectionRow.tsx
- src/components/organisms/Sidebar.tsx
- src/components/templates/IntroSection.tsx
Noto Sans KR이 적용되는 부분 삭제
잘부탁 드립니다. 🙏
> Fix: Noto Sans Kr 및 모바일 환경에서 Article Card Margin 값 수정

- public/robots.txt
stage에 배포할때 Robots.txt가 삭제되서 메인에 머지됐습니다 ㅠㅠ 
메인에만 따로 robots.txt 파일 추가합니다!
🙏
> Fix: robots.txt Upload File

- src/components/atoms/Badge.tsx
- src/components/molecules/ArticleCard.tsx
- src/hooks/api/useGetSectionDetail.ts
- src/pages/course/[courseSlug]/[sectionSlug]/index.tsx
- src/utils/favicon.ts
클랩이 선정한 아티클을 보여주는 클랩픽 기능 추가!
잘 부탁드립니다.!  🙏
> Feature/clelab pick 추가

- src/pages/course/[courseSlug]/[sectionSlug]/index.tsx
- src/pages/course/[courseSlug]/index.tsx
(경고 부분은 이미지랑 headline 적는 부분이라 썸네일 이미지와 같은 부분들은 들어갈 필요가 없을거같아서 제외했습니다! 문제는 없는것같아요!)
총 적용된 부분은 클랩에 course와 section 부분에 적용되었습니다.
구글 서치콘솔에서 제안하는 course 타입을 사용했으며 문서는 아래와 같습니다!
https://developers.google.com/search/docs/advanced/structured-data/course?hl=ko
ld json schema 셋팅을 처음 해봐서 실수가 있을 수 있습니다 잘 부탁드립니다!
잘 부탁드립니다! 🙏
> Feat: Clelab ld+json schema 수정

- .github/workflows/pr-notification.yml
Lubycon/github-reviewer-noti-action@v2.0.3 버전 업데이트
> chore: noti version 2.0.3 버전 업데이트

- src/utils/redirectUrl.ts
Clelab팀이 이번에 구글 검색 노출에 유리하게 하기 위해서 url slug에 한글 + 영어를 지원하기로 결정했습니다!
기존에 url 변경 작업을 했던 Redirect 코드에서 새로운 url로 변경해주는 코드를 추가했습니다
잘 부탁드립니다.!!!
> Feature/Redirect 되야할 URL 추가

- src/utils/redirectUrl.ts
한글 URL일 경우 redirect 못하는 버그가 있었는데 해당 버그 수정했습니다 ㅠㅠ
기존에 validation 체크 하는 부분을 Object key로 해당 url 이 있는지 확인하게 수정했습니다 이 로직 어떠신가요??
잘 부탁 드립니다!
> Release: [Fix] 한글 URL은 redirect 못하는 버그 수정

- src/components/atoms/ClapButton/templates/Medium/index.tsx
-  style clab 박수 qa 결과 반영
- padding 제거 및 svg 교체
- 풍선 컬러 변경
> fix: style clab 박수 qa 결과 반영
